// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIqwhZM65pwp9jJqpCoG-EnFGkOJZob3Y',
    appId: '1:26516352696:web:2cc5b3e7905b0b066e0e4d',
    messagingSenderId: '26516352696',
    projectId: 'recipes-just-for-you',
    authDomain: 'recipes-just-for-you.firebaseapp.com',
    storageBucket: 'recipes-just-for-you.appspot.com',
    measurementId: 'G-BV9RW83J6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBxWC3dIgjd6pHdSEGdTT_883CQMZkgx0',
    appId: '1:26516352696:android:f7794036c928b8676e0e4d',
    messagingSenderId: '26516352696',
    projectId: 'recipes-just-for-you',
    storageBucket: 'recipes-just-for-you.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB33BrgbVA3oG4uAmBnK1k7gZDcDNFvbhM',
    appId: '1:26516352696:ios:78381cb0881d66e46e0e4d',
    messagingSenderId: '26516352696',
    projectId: 'recipes-just-for-you',
    storageBucket: 'recipes-just-for-you.appspot.com',
    iosClientId: '26516352696-1atn5gruea2ib5a024ghq2p08d0hiu85.apps.googleusercontent.com',
    iosBundleId: 'chumspacecoding.com.recipesJustForYou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB33BrgbVA3oG4uAmBnK1k7gZDcDNFvbhM',
    appId: '1:26516352696:ios:74bf3b2a453888aa6e0e4d',
    messagingSenderId: '26516352696',
    projectId: 'recipes-just-for-you',
    storageBucket: 'recipes-just-for-you.appspot.com',
    iosClientId: '26516352696-ktn4cvl4i94p2vadbboru354p6k6a7jb.apps.googleusercontent.com',
    iosBundleId: 'chumspacecoding.com.recipesJustForYou.RunnerTests',
  );
}
